name: Fastify Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: ./batect install-dep

      - name: Run Test Cases
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect lint
