name: Fastify Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Fastify Dependencies
        run: ./batect sudo install-dep

      - name: Run testcase
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect lint
